"""widen confidence column

Revision ID: 00814c2093b5
Revises: 20260515_0002
Create Date: 2026-05-17 04:25:11.220046
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '00814c2093b5'
down_revision: Union[str, None] = '20260515_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'confidence_score',
               existing_type=sa.NUMERIC(precision=6, scale=5),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'confidence_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=5),
               existing_nullable=True)
    # ### end Alembic commands ###

